### ISSUE TITLE
None of the sites work/show what they are supposed to

### ISSUE THREAD

**Issue by gwetson** [Tonemon/UBank#4]
Great work i must confess it must have taken you a whole lot of time and energy to develop this piece..
However the front-end?ouchh!!!
Anyways i would love you elucidate more on the connection to db because i followed your instructions and yet can't get access to the 1. user account dashboard  2. admin dashboard 3. Staff account dashboard (Even after using all default username/password you stated in the review/installation section of the "read me" page that comes with the download) 4. Register New Account isn't functionality...

Please try as urgent and hope to get some help...Thanks

Great job i must confess
![Ubank](https://user-images.githubusercontent.com/39162955/64080157-30d59880-ccf1-11e9-8437-6291a1bd6df4.png)

**Comment by Tonemon** [comment]
Hi, thank you for trying out my new system! I hope you followed my guide I added at the bottom of the README.md page. As i can see from your screenshot you are not on my page but on someone else's page who claimed the official ubank.me domain.

I guess the fix here is the ```hosts``` file. Did you add the following two lines to the ```C:\Windows\System32\drivers\etc\hosts``` file?
<pre>
127.0.0.1       ubank.me
127.0.0.1       account.ubank.me
</pre>

If you did you can clear your firefox cache/session information by going to settings > Privacy & security > cookies and site data > cached web content. I hope this helps!
