### ISSUE TITLE
Malvertising

### ISSUE THREAD

**Issue by k7n2g** [Tonemon/UBank#6]
Hi This looks an interesting project unfortunately  it seems to contains malvertising virus in [account.ubank.me](https://github.com/Tonemon/UBank/tree/master/account.ubank.me)

**Comment by Tonemon** [comment]
Hi, I made this website as an exercise to learn PHP a long while ago so it probably contains a lot of bugs and should not be used in production 😄. Could you be more specific as to where the malvertising virus is?

**Comment by k7n2g** [comment]
Hi Tony Sorry not complaining about a bug just wanted to let you know that ubank.me and account.ubank.me  redirect to malware sites .
Have uploaded the repo and appreciate the code is out of date but still a good effort and very pleasing website although cannot seem to connect from  ubank.me to to  account.ubank.me  redirects to suspicious sites with both google and malwarebytes, i changed the domain names to overcome this but still cant connect both websites, php i am trying to learn  everything i have been doing is with c++  any help as to what i am doing wrong would be helpful sir and thank you for taking the time to reply k7n2g
